---
:default:
    :servers:
        :local: 213131:8081
        :test: ____:0000
    :response_timeout: 1
    :log_level: info
    :log_file: ~/.rogue-craft/rogue-craft.log
    :cache_dir:
        :nix: ~/.rogue-craft/cache
        :windows: null

:local:
    :log_level: debug
    :log_file: ./rogue-craft.log
    :cache_dir:
        :nix: ./.cache
        :windows: cache
