---
default:
    servers:
        development:
          host: localhost:8081
          hint: Your development server running locally
        test:
          host: ____:0000
          hint: Beta test server
    response_timeout: 50
    log_level: info
    log_file: ~/.rogue-craft/rogue-craft.log
    cache_dir:
        nix: ~/.rogue-craft/cache
        windows: null

development:
    log_level: debug
    log_file: ./rogue-craft.log
    cache_dir:
        nix: ./.cache
        windows: cache
